version: '3.8'
services:
  api:
    build: .
    working_dir: /app
    volumes:
      - '.:/app'
    ports:
      - '8000:8000'
    command: php artisan serve --host 0.0.0.0

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secretrootpassword
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database
    ports:
      - '3306:3306'

