<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class IpLogsTest extends TestCase
{
    use RefreshDatabase;

    protected $endpoint;
    protected $user;
    protected $headers;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $payload = [
            'name' => 'Joe Pistone',
            'email' => 'joe@pistone.com',
            'password' => 'password',
            'password_confirmation' => 'password'
        ];
        $this->headers = ['Accept'=> 'application/json'];
        $this->user = $this->post('/api/register',$payload, $this->headers);
    }

    /** @test */
    public function can_ip_log_when_user_logs_in()
    {
        $payload = [
            'email' => $this->user->json('user')['email'],
            'password' => 'password'
        ];
        $this->assertDatabaseMissing('logs',
           ['user_id' =>$this->user->json('user')['id']]);

        $this->post('/api/login', $payload, $this->headers);

        $this->assertDatabaseHas('logs',
            ['user_id' =>$this->user->json('user')['id']]);

    }
}
